---
folders:
  Button:
    components:
      - Button
  Form:
    components:
      - Select
      - TextInput
      - TextArea

components:
  Button: {}
  Select: {}
  TextArea: {}
  TextInput:
      isClassComponent: true
      isTestInSameDirectory: true

